fixed workflow

diff --git a/.github/workflows/provision.yml b/.github/workflows/provision.yml
--- a/.github/workflows/provision.yml
+++ b/.github/workflows/provision.yml
@@ -34,12 +34,21 @@ jobs:
       - name: Terraform Apply (infra)
         working-directory: ./terraform
         run: terraform apply -auto-approve -var="bucket_name=${{ github.event.client_payload.bucket }}" -var="lambda_name=${{ github.event.client_payload.lambda }}"
+   
+      - name: Show Terraform Outputs
+        working-directory: ./terraform
+        run: terraform output
 
       # ✅ Get ECR repo URL from Terraform output
       - name: Get ECR Repo URL
         working-directory: ./terraform
         run: |
-          echo "ECR_REPO=$(terraform output -raw ecr_repo_url)" >> $GITHUB_ENV
+          ECR_REPO=$(terraform output -raw ecr_repo_url)
+          if [ -z "$ECR_REPO" ]; then
+            echo "ECR_REPO is empty. Terraform output missing."
+            exit 1
+          fi
+          echo "ECR_REPO=$ECR_REPO" >> $GITHUB_ENV
 
       # ✅ Login AFTER repo exists
       - name: Login to Amazon ECR
